/**
 * GitHub Action entrypoint for PR Slop Filter
 *
 * Reads PR context from @actions/github, runs all 3 detection modules,
 * sets outputs, creates annotations, and optionally posts a PR comment.
 */

import * as core from '@actions/core';
import * as github from '@actions/github';
import { runFilter } from '../index.js';
import type { FilterConfig, SlopReport } from '../types.js';

// ── Helpers ────────────────────────────────────────────────────────

function severityToAnnotationLevel(
  sev: 'flag' | 'warning' | 'info',
): 'error' | 'warning' | 'notice' {
  return sev === 'flag' ? 'error' : sev === 'warning' ? 'warning' : 'notice';
}

function buildComment(report: SlopReport): string {
  const verdictEmoji: Record<string, string> = {
    human: '✅',
    uncertain: '❓',
    'likely-slop': '⚠️',
    slop: '🚩',
  };
  const emoji = verdictEmoji[report.verdict] ?? '❓';

  const moduleRows = report.modules
    .map((m) => {
      const bar = scoreBarSimple(m.score);
      return `| ${m.module} | ${bar} ${m.score}/100 | ${m.findings.length} | ${m.duration_ms}ms |`;
    })
    .join('\n');

  const topFindings = report.modules
    .flatMap((m) => m.findings)
    .sort((a, b) => b.score - a.score)
    .slice(0, 8)
    .map((f) => {
      const icon = f.severity === 'flag' ? '🚩' : f.severity === 'warning' ? '⚠️' : 'ℹ️';
      return `- ${icon} **${f.module}**: ${f.message}`;
    })
    .join('\n');

  return `## ${emoji} PR Slop Filter Report

**Score:** ${report.overall_score}/100 — **${report.verdict.toUpperCase()}**
**Confidence:** ${report.confidence}%

### Module Breakdown

| Module | Score | Findings | Time |
|--------|-------|----------|------|
${moduleRows}

${topFindings.length > 0 ? `### Top Findings\n\n${topFindings}\n` : ''}
<details>
<summary>Raw JSON</summary>

\`\`\`json
${JSON.stringify(report, null, 2)}
\`\`\`
</details>

---
<sub>🤖 Generated by <a href="https://github.com/noxlie/pr-slop-filter">PR Slop Filter</a></sub>`;
}

function scoreBarSimple(score: number, width = 10): string {
  const filled = Math.round((score / 100) * width);
  const empty = width - filled;
  return '`' + '█'.repeat(filled) + '░'.repeat(empty) + '`';
}

// ── Main action ────────────────────────────────────────────────────

async function run(): Promise<void> {
  try {
    // Read inputs
    const threshold = parseInt(core.getInput('threshold') || '70', 10);
    const failOnSlop = core.getInput('fail-on-slop').toLowerCase() === 'true';
    const format = (core.getInput('format') || 'github-annotation') as FilterConfig['format'];
    const llmProvider = core.getInput('llm-provider') || undefined;
    const llmApiKey = core.getInput('llm-api-key') || undefined;
    const llmModel = core.getInput('llm-model') || undefined;

    const config: FilterConfig = {
      threshold,
      fail_on_slop: failOnSlop,
      verbose: false,
      format,
      github_token: process.env.GITHUB_TOKEN,
      llm_provider: llmProvider as FilterConfig['llm_provider'],
      llm_api_key: llmApiKey,
      llm_model: llmModel,
    };

    // Get PR context from the action event
    const prContext = github.context.payload.pull_request;
    if (!prContext) {
      core.setFailed('This action only works on pull_request events.');
      return;
    }

    const { owner, repo } = github.context.repo;
    const prNumber = prContext.number;

    core.info(`Checking PR #${prNumber} in ${owner}/${repo}...`);

    // Build PRContext from GitHub event payload
    const pr: import('../types.js').PRContext = {
      owner,
      repo,
      pr_number: prNumber,
      title: prContext.title ?? '',
      body: prContext.body ?? '',
      author: prContext.user?.login ?? 'unknown',
      commits: [], // Will be populated by modules that need it
      files_changed: [], // Will be populated by modules that need it
      labels: (prContext.labels as Array<{ name?: string }>)?.map(
        (l) => l.name ?? '',
      ),
      base_branch: prContext.base?.ref ?? 'main',
      head_branch: prContext.head?.ref ?? '',
    };

    // If we have a GitHub token, fetch full PR data via API
    if (process.env.GITHUB_TOKEN) {
      try {
        const octokit = github.getOctokit(process.env.GITHUB_TOKEN);

        const { data: fullPR } = await octokit.rest.pulls.get({
          owner,
          repo,
          pull_number: prNumber,
        });

        const { data: commits } = await octokit.rest.pulls.listCommits({
          owner,
          repo,
          pull_number: prNumber,
          per_page: 100,
        });

        const { data: files } = await octokit.rest.pulls.listFiles({
          owner,
          repo,
          pull_number: prNumber,
          per_page: 100,
        });

        pr.body = fullPR.body ?? '';
        pr.author = fullPR.user?.login ?? 'unknown';
        pr.author_account_age_days = undefined; // Would need separate user API call
        pr.commits = commits.map((c) => ({
          sha: c.sha,
          message: c.commit.message?.split('\n')[0] ?? '',
          author: c.commit.author?.name ?? 'unknown',
          date: c.commit.author?.date ?? '',
        }));
        pr.files_changed = files.map((f) => ({
          filename: f.filename,
          status: f.status as import('../types.js').FileChange['status'],
          additions: f.additions,
          deletions: f.deletions,
          patch: f.patch,
        }));
      } catch (err) {
        core.warning(
          `Could not fetch full PR data: ${err instanceof Error ? err.message : String(err)}. Using payload data.`,
        );
      }
    }

    // Run the filter
    const report = await runFilter(pr, config);

    // Set outputs
    core.setOutput('slop-score', report.overall_score.toString());
    core.setOutput('verdict', report.verdict);
    core.setOutput('summary', report.summary);

    // Create annotations for findings
    for (const mod of report.modules) {
      for (const f of mod.findings) {
        const level = severityToAnnotationLevel(f.severity);
        const message = `[slop:${f.module}] ${f.message}${f.detail ? ` — ${f.detail}` : ''}`;
        // Emit annotation
        switch (level) {
          case 'error':
            core.error(message, { title: `PR Slop: ${f.module}` });
            break;
          case 'warning':
            core.warning(message, { title: `PR Slop: ${f.module}` });
            break;
          default:
            core.notice(message, { title: `PR Slop: ${f.module}` });
        }
      }
    }

    // Post a comment on the PR if we have a token
    if (process.env.GITHUB_TOKEN) {
      try {
        const octokit = github.getOctokit(process.env.GITHUB_TOKEN);
        const body = buildComment(report);

        // Check for existing bot comment to update
        const { data: comments } = await octokit.rest.issues.listComments({
          owner,
          repo,
          issue_number: prNumber,
          per_page: 100,
        });

        const existingComment = comments.find(
          (c) =>
            c.user?.type === 'Bot' &&
            c.body?.includes('PR Slop Filter Report'),
        );

        if (existingComment) {
          await octokit.rest.issues.updateComment({
            owner,
            repo,
            comment_id: existingComment.id,
            body,
          });
          core.info('Updated existing slop report comment.');
        } else {
          await octokit.rest.issues.createComment({
            owner,
            repo,
            issue_number: prNumber,
            body,
          });
          core.info('Posted slop report comment on PR.');
        }
      } catch (err) {
        core.warning(
          `Could not post PR comment: ${err instanceof Error ? err.message : String(err)}`,
        );
      }
    }

    // Log summary
    core.info('');
    core.info(report.summary);
    core.info('');

    // Fail if needed
    if (failOnSlop && report.overall_score >= threshold) {
      core.setFailed(
        `Slop score ${report.overall_score}/100 exceeds threshold ${threshold}. Verdict: ${report.verdict}`,
      );
    } else {
      core.info(
        `✅ Slop score ${report.overall_score}/100 is below threshold ${threshold}.`,
      );
    }
  } catch (err) {
    core.setFailed(
      `PR Slop Filter failed: ${err instanceof Error ? err.message : String(err)}`,
    );
  }
}

run();
